### ISSUE TITLE
Please Restart you're API

### ISSUE THREAD

**Issue by Zaeem20** [Blad3Mak3r/RedditMemes#144]
hey bro you're api is amazing i, was using it from a quarter but i observed now that my bot meme command is not working can you please check it out..

**Comment by Blad3Mak3r** [comment]
If you're using the HTTP API thats is down, you can use the Deno based api https://memes-v2.blademaker.tv/ (https://github.com/Blad3Mak3r/DenoMemes)

**Comment by Zaeem20** [comment]
But it not support custom Subreddit category route like previous one... If yes tell me how do I do it

**Comment by Blad3Mak3r** [comment]
It is possible, just use https://memes-v2.blademaker.tv/r/meirl (for example)
